#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
line="\\\t location{\nrewrite ^/redirect_me http://myhang.tech permanent;\n}"
sudo sed -i "13i $line" /etc/nginx/sites-available/myhang.tech
sudo service nginx restart