#!/usr/bin/env bash
# Make a backup of the databases
# Define variables
DB_USER="root"
#BACKUP_DIR="~/"

# Generate filename
DATE=$(date +"%d-%m-%Y")
FILENAME="backup.sql"

# Generate MySQL dump
mysqldump --user="${DB_USER}" --password="$1" --all-databases > "${FILENAME}"

# Compress the dump
tar -zcf "${DATE}.tar.gz" "${FILENAME}"

# Delete the original dump
#rm "${FILENAME}"
