#!/usr/bin/env bash
# Reconfigure nginx
sed  '/location \/hbnb_static/i location /airbnb-onepage { alias /data/web_static }' /etc/nginx/sites-available/default 
sed -i 'try_files include proxy_params\;\nproxy_pass http://127.0.0.1:5000\;' /etc/nginx/sites-available/default 
service nginx restart

